### ISSUE TITLE
Bug in contig orientation

### ISSUE THREAD

**Issue by zorino** [ablab-nthu/CSAR#1]
Hi I think I've found a bug in the contig orientation output : scaffolds.nuc.csar

*1 - If I take a contig and do a csar on itself it give the orientation 1 ..
*2 - If I take the reverse complement of the sequence and csar it to the original sequence, it still gives 1 as the contig orientation ..

A contig against itself (*1) shouldn't give orientation 1 but 0 

Thanks for helping with this

**Comment by holystu** [comment]
Thanks for the kindly feedback.
I have modified the code for the issue you mentioned.
Please clone/download CSAR again.

BTW, since we could consider a scaffold as a single chromosome,  its two different orientations (forward and reverse) would have the same meaning in the result.
That is to say, in two different results of CSAR,
```
>Scaffold_1
contig_1 0
contig_2 0
```
is equal to
```
>Scaffold_1
contig_2 1
contig_1 1
```
Thank you for using CSAR and welcome any suggestions.

**Comment by zorino** [comment]
I understand that the scaffold even if not in the same orientation would still be valid.

But I believe it's expected that the scaffold be in the same orientation than the reference's strain, otherwise it's misleading. 

OK now with your last commit it just always gives 0 instead of 1 for the orientation, can you modify so it takes the orientation of the reference's sequence instead ?
Thank you

**Comment by holystu** [comment]
Hi, I've modified the code for your asking and committed it as a new branch.
Please refer the branch ["issue#1"](https://github.com/ablab-nthu/CSAR/tree/issue%231).

Note that, in CSAR, the orientation of a contig in a scaffold is relative to its original one in the input.
Think of that what if half of the sequence in a contig is mapped to the forward strand of a reference, and the other half is mapped to the opposite strand.

**Comment by zorino** [comment]
Hi thank you for the branch

I understand your concern about the orientation, but instinctively I would always take the orientation from the start of the reference. If there's an inversion in the target it would be easily spotted afterward and at least both the reference and the target would start at the same position.
